version: "3"

volumes:
  productdata:

networks:
  frontend:
  backend:

services:
  
  mysql:
    image: "mysql:8.0"
    volumes:
      - productdata:/var/lib/mysql
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=pwd
      - bind-address=0.0.0.0

  dbinit:
    image: "jakobleer/sandbox:4.0"
    networks:
      - backend
    environment:
      - INITDB=true
      - DBHOST=mysql
    depends_on:
      - mysql

  mvc:
    image: "jakobleer/sandbox:4.0"
    networks:
      - backend
      - frontend
    environment:
      - DBHOST=mysql
    depends_on:
      - mysql

  loadbalancer:
    image: "dockercloud/haproxy"
    ports:
      - 3000:80
    links:
      - mvc
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - frontend
