version: "3"

volumes:
  productdata:

networks:
  backend:

services:
  
  mysql:
    image: "mysql:8.0"
    volumes:
      - productdata:/var/lib/mysql
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=pwd
      - bind-address=0.0.0.0

  mvc:
    image: "jakobleer/sandbox:dev"
    volumes:
      - /Projects/dotnet-core/dotnetcore-and-docker:/app
      - /app/obj
      - /app/bin
      - ~/.nuget:/root/.nuget
      - /root/.nuget/packages/.tools
    ports:
      - 3000:80
    networks:
      - backend
    environment:
      - DBHOST=mysql
      - WAITHOST=mysql
    depends_on:
      - mysql
